version: "3.9"
services:
  flash:
    container_name: flash
    build: .
    ports:
      - "25565:25565"
    restart: always
    volumes:
      - ../target/flash.jar:/opt/paper/plugins/flash.jar
      - ../maps/spawn:/opt/paper/spawn
      - ../worlds:/opt/paper/plugins/Flash/maps
